package com.iyxan23.asperge.swproject.view

data class ViewItem(
    val adSize: String,
    val adUnitId: String,
    val alpha: Float,
    val checked: Int,
    val choiceMode: Int,
    val clickable: Int,
    val customView: String,
    val dividerHeight: Int,
    val enabled: Int,
    val firstDayOfWeek: Int,
    val id: String,
    val image: ,
    val indeterminate: String,
    val index: Int,
    val layout: ,
    val max: Int,
    val parent: String,
    val parentType: Int,
    val preId: String,
    val preIndex: Int,
    val preParentType: Int,
    val progress: Int,
    val progressStyle: String,
    val scaleX: Float,
    val scaleY: Float,
    val spinnerMode: Int,
    val text: ,
    val translationX: Float,
    val translationY: Float,
    val type: Int
)
